# Generated by Django 3.1.4 on 2021-05-06 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=30)),
                ('car_model', models.CharField(max_length=30)),
                ('car_class', models.CharField(max_length=30)),
                ('gear_box', models.CharField(max_length=30)),
                ('number_auto', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Time_and_Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_and_price', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.CharField(blank=True, max_length=20, unique=True)),
                ('car_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('car_brand', models.CharField(max_length=30)),
                ('car_model', models.CharField(max_length=20)),
                ('time_and_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KursRabota.time_and_price')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.CharField(max_length=9, unique=True)),
                ('tel_number', models.IntegerField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
